// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateShape('topRectangleShape', { rightImageWidth: 12, leftImageWidth: 12 });
    CreateShape('bottomRectangleShape', { rightImageWidth: 12, leftImageWidth: 12 });
    CreateScrollArea('contentarea', { spacing: 11, leftMargin: 11, rightMargin: 7, hasVerticalScrollbar: true, autoHideScrollbars: true });
    CreateText('loading-text', { text: 'Loading' });
    CreateText('text', { text: 'Service Disruptions' });
    CreateText('text1', { text: 'WMATA Service Disruption Dashboard Widget' });
    CreateText('updatedText', {  });
}
window.addEventListener('load', setupParts, false);
