// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
var attributes = {
    feedURL: 'http://www.wmata.com/wmataRSS20.xml',
    numItemsToShow: "-1",
    maxAgeToShow: "-1",
    showDate: "1",
    showUpdateBadge: '1'
};
